apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: alpine/curl
    command: ["sleep", "3600"]
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
      type: Socket