when:
  - event: push
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

steps:
  - name: build
    image: node:24.8.0-trixie
    environment:
      HEAD_SHA: ${CI_COMMIT_SHA}
    commands:
      - git fetch --no-tags --prune origin main
      - git checkout -B main origin/main
      - |
          if [ "${CI_PIPELINE_EVENT}" = "pull_request" ]; then
            TARGET_BRANCH="origin/${CI_COMMIT_REF}"
            git fetch origin $TARGET_BRANCH
            BASE_SHA=$(git merge-base $TARGET_BRANCH $HEAD_SHA)
          else
            BASE_SHA=$(git rev-parse HEAD~1)
          fi
          echo "BASE_SHA=$BASE_SHA" >> /woodpecker/envvars
          echo "HEAD_SHA=$HEAD_SHA" >> /woodpecker/envvars
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm config set store-dir /pnpm-store
      - ls -la /pnpm-store
      - pnpm install
      - pnpm affected:build --base=$BASE_SHA --head=$HEAD_SHA
    volumes:
      - pnpm-store:/pnpm-store
  - name: build-docker-images
    image: node:24.8.0-trixie
    environment:
      BUILD_TAG: ${CI_COMMIT_SHA:0:8}
    commands:
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm config set store-dir /pnpm-store
      - pnpm install
      - pnpm nx run foobar-api:docker:build
    volumes:
      - pnpm-store:/pnpm-store
    depends_on: [build]

  - name: publish-foobar-api
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: example.org/foobar-api
      tags: latest,${CI_COMMIT_SHA:0:8}
    depends_on: [build-docker-images]