when:
  - event: push
    branch: main

steps:
  - name: build
    image: node:24.8.0
    commands:
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm install
      - pnpm affected:build