when:
  - event: push
    branch: main

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
       partial: false
       depth: 50

steps:
  - name: build
    image: node:24.8.0
    commands:
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm install
      - pnpm affected:build