when:
  - event: push
    branch: main

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      depth: 100
      
steps:
  - name: build
    image: node:24.8.0-trixie
    commands:
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm config set store-dir /pnpm-store
      - ls -la /pnpm-store
      - pnpm install
      - pnpm affected:build
    volumes:
      - pnpm-store:/pnpm-store