when:
  - event: push
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

steps:
  - name: build
    image: node:24.8.0-trixie
    commands:
      - git fetch origin main
      - git checkout -B main origin/main
      - corepack enable && corepack prepare pnpm@latest --activate
      - pnpm config set store-dir /pnpm-store
      - ls -la /pnpm-store
      - pnpm install
      - pnpm affected:build
    volumes:
      - pnpm-store:/pnpm-store